#!/usr/bin/env bash
# This script displays information about subdomains of a given domain

domain="$1"
subdomain="$2"

if [ -z "$subdomain" ]; then
    subdomains=("www" "lb-01" "web-01" "web-02")
else
    subdomains=("$subdomain")
fi

for sub in "${subdomains[@]}"; do
    output=$(dig "$sub.$domain" | awk '/^'${sub}'\.'"$domain"'/ {print $5}')
    record_type=$(dig "$sub.$domain" | awk '/^'${sub}'\.'"$domain"'/ {print $4}')
    echo "The subdomain $sub is a $record_type record and points to $output"
done