#!/usr/bin/env bash
# installing nginx, listening on port 80

apt-get update
apt-get install -y nginx

ufw allow 'Nginx HTTP'
chmod -R 755 /var/www
echo 'Hello World!' > /var/www/html/index.html
if [ "$(pgrep -c nginx)" -le 0 ]; then
	service nginx start
else
	service nginx restart
fi
