#!/usr/bin/env bash

# Update and upgrade installed packages
sudo apt-get update
sudo apt-get upgrade -y

# Install Nginx
sudo apt-get install nginx -y

# Configure Nginx to include the custom HTTP response header
echo 'add_header X-Served-By $hostname;' | sudo tee -a /etc/nginx/nginx.conf

# Restart Nginx to apply changes
sudo systemctl restart nginx
